SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ROLE_PERMISSIONS;
DROP TABLE IF EXISTS ST_CITY;
DROP TABLE IF EXISTS ST_PERMISSIONS;
DROP TABLE IF EXISTS ST_ROLE;
DROP TABLE IF EXISTS ST_SCENIC;
DROP TABLE IF EXISTS ST_USER;




/* Create Tables */

CREATE TABLE ROLE_PERMISSIONS
(
	ID VARCHAR(40) NOT NULL,
	ROLE_ID VARCHAR(40),
	PERMISSION_ID VARCHAR(40),
	PRIMARY KEY (ID)
);


CREATE TABLE ST_CITY
(
	ID INT NOT NULL,
	CODE VARCHAR(9),
	NAME VARCHAR(36),
	PARENT_ID INT,
	FIRST_LETTER VARCHAR(4),
	LEVEL INT,
	PRIMARY KEY (ID)
);


CREATE TABLE ST_PERMISSIONS
(
	ID VARCHAR(40) NOT NULL,
	PARENT_ID VARCHAR(40),
	PERMISSION VARCHAR(20),
	PRIMARY KEY (ID)
);


CREATE TABLE ST_ROLE
(
	ID VARCHAR(40) NOT NULL,
	ROLE_NAME VARCHAR(20),
	USER_ID VARCHAR(40),
	PRIMARY KEY (ID)
);


CREATE TABLE ST_SCENIC
(
	ID VARCHAR(40) NOT NULL,
	CITY_ID VARCHAR(40),
	NAME VARCHAR(30),
	ADDRESS VARCHAR(40),
	PRINCIPAL VARCHAR(10),
	EMAIL VARCHAR(20),
	TEL VARCHAR(20),
	description VARCHAR(200),
	USER_ID VARCHAR(40),
	STATE INT(1),
	PRIMARY KEY (ID)
);


CREATE TABLE ST_USER
(
	ID VARCHAR(40) NOT NULL,
	USERNAME VARCHAR(40),
	PASSWORD VARCHAR(40),
	EMAIL VARCHAR(20),
	TEL VARCHAR(20),
	CITY_ID VARCHAR(40),
	STATE INT(1),
	CODE VARCHAR(40),
	-- 1. 最高权限的管理员 2.普通录入源 
	TYPE INT(1) COMMENT '1. 最高权限的管理员 2.普通录入源 ',
	PARENT_ID VARCHAR(40),
	PRIMARY KEY (ID)
);



